kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-node-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 3000 # Forward to port 3000 on the Pods
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: node-app2 # Match the label applied to the Pods by the Deployment[template.metadata.labels.app]
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer