
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: my-node-app
spec:
  # 3 Pods should exist at all times.
  replicas: 5
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: node-app2
    spec:
      containers:
      - name: node-app2
        # Run this image
        image: mstsurnalyakte/node-demo-app:01