# config map file for mongo db connection details
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_HOST: service-mongo-app
  MONGO_PORT: "27017"
  MONGO_DB_NAME: yourDatabaseName