apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: mongo:latest
        # ports:
        # - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: service-mongo-app
spec:
  selector:
    app: mongo-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
